#version: '3.8' # it's not necessary to add anymore.

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_USER=${Database_user}  # username
      - POSTGRES_PASSWORD=${Database_pass} # database password
      - POSTGRES_DB=${Database_name} # database name
      - POSTGRES_HOST=${Database_host} # hostname will be db for docker and localhost for local project.
      - POSTGRES_PORT=${Database_port} # port number
    depends_on:
      - db
  db:
    image: postgres:17 # postgres version
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${Database_name} # database name
      - POSTGRES_USER=${Database_user}  # username
      - POSTGRES_PASSWORD=${Database_pass} # database password
    ports:
      - "5432:5432"


volumes:
  postgres_data:
    external: true
