#version: '3.8' # it's not necessary to add anymore.

services:

  web:
    build: ./backend
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${Database_user} 
      - POSTGRES_PASSWORD=${Database_pass}
      - POSTGRES_DB=${Database_name} 
    depends_on:
      - db

  db:
    image: postgres:17 # postgres version
    hostname: postgres_db_expense_tracker
    volumes:
      - expense-tracker-backend_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${Database_user} 
      - POSTGRES_PASSWORD=${Database_pass} 
      - POSTGRES_DB=${Database_name} 

volumes:
  expense-tracker-backend_db_data:
    external: true
